### ISSUE TITLE
Copy-past feature

### ISSUE THREAD

**Issue by CoCoSol007** [rparrett/bevy_simple_text_input#16]
you should add a system for copying and pasting text into text input

**Comment by rparrett** [comment]
That's an important feature, but I think that's going slightly beyond the scope of this project for me.

It's very possible, but I don't want to maintain that code, and I want to keep this simple for folks to modify as they see fit.

Roughly what would need to be done:

- In the key handling code, check if ctrl is held while v is pressed. (or command on mac)
- For native platforms, use the `clipboard` crate or similar to read the clipboard.
- On the web, use `web-sys` and a bunch of [scary async stuff](https://github.com/rparrett/bevy_wordle_viz/blob/main/src/wasm_clipboard.rs).
- Add the string you receive to the end of `text.sections[0].value`

**Comment by vveisard** [comment]
@rparrett I'm trying to implement this functionality like you said. 

>Add the string you receive to the end of text.sections[0].value

I'm looking at the `update_value` system in source as an example which uses `InnerText` system param and `set_section_values` helper function. These are not exported by the crate. Or am I mistaken on how I should implement this.

**Comment by ironpeak** [comment]
Incase someone finds it useful, I've implemented paste here:
https://github.com/ironpeak/bevy_simple_text_input/commit/f8262c05454d849df5dcec45bea02d8d62f9e463
