### ISSUE TITLE
wasm: backspace and enter don't work

### ISSUE THREAD

**Issue by rparrett** [rparrett/bevy_simple_text_input#2]
`winit` doesn't send `ReceivedCharacter` events for these on the web.

So we need to use `KeyboardInput` events for these. This is unfortunate because the separate event streams can cause timing issues. In another project, to fix these timing issues, I resorted to using `KeyboardInput` for everything, but this came at the expense of easy international keyboard support.

So I think switching backspace and enter to `KeyboardInput` is the right call for now, potentially only for wasm if that doesn't complicate things too much.

This is fixed in winit 0.29 (and hopefully bevy 0.12. see https://github.com/bevyengine/bevy/pull/8745) where these two events are unified into `KeyEvent`.

**Comment by werner291** [comment]
I was about to open an issue about this... Any alternatives in the meantime?
