### ISSUE TITLE
Provide a way for users to set the value of the text input

### ISSUE THREAD

**Issue by rparrett** [rparrett/bevy_simple_text_input#25]
Let's discuss how this might be done without introducing a huge amount of complexity.

**Comment by Leinnan** [comment]
My take:
- Updating the value of the `TextInput` should be enough
- keyboard input updates the `TextInput` component value
- Text Sections are updated on `Changed<TextInput>`
- That would require rethinking how to handle input cursor, maybe use it as an opportunity to introduce text selection? But that would be just a bonus.

**Comment by rparrett** [comment]
That seems worth exploring / testing. I guess cursor position would need to be stored a `usize` either alongside the text value or in another component.

I'm a bit wary because I think we're already dipping our toes onto the slippery slope of no longer being "bevy **simple** text input." And handling the cursor position properly when the user changes the value through `TextInput` or with their keyboards seems tricky. And with users reading/writing this value, it seems like we might need to a way for users to order their systems against ours, or possibly move ours into PostUpdate so things behave consistently.

I feel like text selection would probably be taking things too far.

**Comment by rparrett** [comment]
That seemed to go fairly well. We're only at ~+35 loc for the change and this actually demystifies the text section handling a bit.

I still have some vague reservations that users might see unexpected behavior depending on whether their systems run before or after the `keyboard` system. Seems a bit unlikely to come up in practice, though?
