### ISSUE TITLE
TextInput can't be used with the "require" system

### ISSUE THREAD

**Issue by kim-fg** [rparrett/bevy_simple_text_input#82]
As the title states, TextInput can't be used with the new "require" system. 
I'm attempting to do the following for cleanliness:
```rust
#[derive(Component)]
#[require(TextInput)] // <- Missing Default impl here
struct NameInput;     // <- custom struct used for filtering query
```

I'm using bevy 0.15 for reference.
I'd happily patch this but I'm currently busy with making a game, so just leaving this here as its probably a simple oversight.

If anyone happens to patch this, thanks in advance!

(I also posted a [similar issue](https://github.com/bevyengine/bevy/issues/17052) in the main bevy repository and they may be adding a lint for it in the future, could be neat to keep eyes on for other projects)

**Comment by rparrett** [comment]
Published `0.10.` which includes the fix. Thanks for the report.
