### ISSUE TITLE
Undertanding implementation of `TextInput`

### ISSUE THREAD

**Issue by Operator57** [rparrett/bevy_simple_text_input#9]
I don't undertsand very well why it is needed to spawn a `NodeBundle` together with the `TextInput` if all the input system is embedded in a overflow container and is added as a child to the `TextInput` entity. The `TextInput` solely should render with no problem. However, that panics.

**Comment by rparrett** [comment]
Bevy UI hierarchies require the components of `NodeBundle` to work properly.

The current design where a user spawns both a `NodeBundle` and `TextInput` component together comes from my general aversion to working with nested bundles. That is, this:
```rust
commands.spawn((
    NodeBundle { /* ... */ },
    TextInput { /* ... */ }
))
```
feels a bit nicer to me than
```rust
commands.spawn(TextInputBundle {
    node: NodeBundle { /* ... */ },
    text_input: TextInput { /* ... */ }
})
```
But now that I'm typing this all out, I'm not sure about the decision.

Maybe your instinct is right and we can remove one layer of `NodeBundle`. I think there may have been some slightly surprising behavior with borders / clipping though that made that extra layer necessary though.

**Comment by Operator57** [comment]
Ok, I see. Thank you :) 

Regarding the decision, I think it is clearer to use `TextInputBundle`.
